return {
    [14] = {Name = "Enchanted Angelfish", Tier = 4},
    [15] = {Name = "Abyss Seahorse", Tier = 5},
    [16] = {Name = "Magic Tang", Tier = 4},
    [17] = {Name = "Astra Damsel", Tier = 4},
    [18] = {Name = "Charmed Tang", Tier = 3},
    [19] = {Name = "Coal Tang", Tier = 2},
    [20] = {Name = "Ash Basslet", Tier = 1},
    [21] = {Name = "Hawks Turtle", Tier = 5},
    [22] = {Name = "Blue Lobster", Tier = 4},
    [23] = {Name = "Maze Angelfish", Tier = 3},
    [24] = {Name = "Starjam Tang", Tier = 4},
    [25] = {Name = "Greenbee Grouper", Tier = 4},
    [26] = {Name = "Domino Damsel", Tier = 4},
    [27] = {Name = "Panther Grouper", Tier = 4},
    [28] = {Name = "White Clownfish", Tier = 2},
    [29] = {Name = "Scissortail Dartfish", Tier = 2},
    [30] = {Name = "Tricolore Butterfly", Tier = 2},
    [31] = {Name = "Corazon Damsel", Tier = 1},
    [32] = {Name = "Orangy Goby", Tier = 1},
    [33] = {Name = "Specked Butterfly", Tier = 1},
    [34] = {Name = "Loggerhead Turtle", Tier = 5},
    [35] = {Name = "Prismy Seahorse", Tier = 5},
    [36] = {Name = "Lobster", Tier = 4},
    [37] = {Name = "Bumblebee Grouper", Tier = 4},
    [38] = {Name = "Longnose Butterfly", Tier = 4},
    [39] = {Name = "Sushi Cardinal", Tier = 4},
    [40] = {Name = "Kau Cardinal", Tier = 3},
    [41] = {Name = "Fire Goby", Tier = 2},
    [42] = {Name = "Shrimp Goby", Tier = 2},
    [43] = {Name = "Reef Chromis", Tier = 1},
    [44] = {Name = "Banded Butterfly", Tier = 2},
    [45] = {Name = "Boa Angelfish", Tier = 1},
    [46] = {Name = "Jennifer Dottyback", Tier = 1},
    [47] = {Name = "Blueflame Ray", Tier = 5},
    [48] = {Name = "Lavafin Tuna", Tier = 4},
    [49] = {Name = "Firecoal Damsel", Tier = 4},
    [50] = {Name = "Magma Goby", Tier = 2},
    [51] = {Name = "Volcanic Basslet", Tier = 1},
    [52] = {Name = "Hammerhead Shark", Tier = 5},
    [53] = {Name = "Chrome Tuna", Tier = 4},
    [54] = {Name = "Manta Ray", Tier = 5},
    [55] = {Name = "Moorish Idol", Tier = 4},
    [56] = {Name = "Maroon Butterfly", Tier = 4},
    [57] = {Name = "Cow Clownfish", Tier = 4},
    [58] = {Name = "Vintage Damsel", Tier = 2},
    [59] = {Name = "Candy Butterfly", Tier = 2},
    [60] = {Name = "Jewel Tang", Tier = 2},
    [61] = {Name = "Yellowstate Angelfish", Tier = 1},
    [62] = {Name = "Vintage Blue Tang", Tier = 1},
    [63] = {Name = "Skunk Tilefish", Tier = 1},
    [64] = {Name = "Clownfish", Tier = 1},
    [65] = {Name = "Strawberry Dotty", Tier = 1},
    [66] = {Name = "Azure Damsel", Tier = 1},
    [67] = {Name = "Copperband Butterfly", Tier = 2},
    [68] = {Name = "Flame Angelfish", Tier = 2},
    [69] = {Name = "Yello Damselfish", Tier = 2},
    [70] = {Name = "Dorhey Tang", Tier = 4},
    [71] = {Name = "Darwin Clownfish", Tier = 3},
    [72] = {Name = "Korean Angelfish", Tier = 3},
    [73] = {Name = "Yellowfin Tuna", Tier = 4},
    [74] = {Name = "Unicorn Tang", Tier = 4},
    [75] = {Name = "Dotted Stingray", Tier = 5},
    [82] = {Name = "Blob Shark", Tier = 7},
    [83] = {Name = "Ghost Shark", Tier = 7},
    [86] = {Name = "Slurpfish Chromis", Tier = 2},
    [87] = {Name = "Lava Butterfly", Tier = 2},
    [88] = {Name = "Rockform Cardianl", Tier = 3},
    [89] = {Name = "Volsail Tang", Tier = 3},
    [90] = {Name = "Gingerbread Tang", Tier = 1},
    [91] = {Name = "Mistletoe Damsel", Tier = 1},
    [92] = {Name = "Festive Goby", Tier = 1},
    [93] = {Name = "Christmastree Longnose", Tier = 3},
    [94] = {Name = "Gingerbread Clownfish", Tier = 2},
    [95] = {Name = "Candycane Lobster", Tier = 4},
    [96] = {Name = "Festive Pufferfish", Tier = 4},
    [97] = {Name = "Gingerbread Turtle", Tier = 5},
    [98] = {Name = "Gingerbread Shark", Tier = 6},
    [99] = {Name = "Great Christmas Whale", Tier = 7},
    [106] = {Name = "Blue-Banded Goby", Tier = 2},
    [107] = {Name = "Blumato Clownfish", Tier = 2},
    [108] = {Name = "Conspi Angelfish", Tier = 1},
    [109] = {Name = "Fade Tang", Tier = 1},
    [110] = {Name = "Lined Cardinal Fish", Tier = 5},
    [111] = {Name = "Masked Angelfish", Tier = 1},
    [112] = {Name = "Pygmy Goby", Tier = 1},
    [113] = {Name = "Sail Tang", Tier = 1},
    [114] = {Name = "Watanabei Angelfish", Tier = 1},
    [115] = {Name = "White Tang", Tier = 1},
    [116] = {Name = "Zoster Butterfly", Tier = 1},
    [117] = {Name = "Bandit Angelfish", Tier = 2},
    [119] = {Name = "Ballina Angelfish", Tier = 3},
    [120] = {Name = "Pink Smith Damsel", Tier = 2},
    [121] = {Name = "Bleekers Damsel", Tier = 2},
    [122] = {Name = "Loving Shark", Tier = 6},
    [135] = {Name = "Patriot Tang", Tier = 1},
    [136] = {Name = "Frostborn Shark", Tier = 7},
    [137] = {Name = "Plasma Shark", Tier = 5},
    [138] = {Name = "Axolotl", Tier = 4},
    [139] = {Name = "Silver Tuna", Tier = 2},
    [140] = {Name = "Pilot Fish", Tier = 2},
    [141] = {Name = "Great Whale", Tier = 7},
    [142] = {Name = "Orange Basslet", Tier = 2},
    [143] = {Name = "Pufferfish", Tier = 4},
    [144] = {Name = "Racoon Butterfly Fish", Tier = 2},
    [145] = {Name = "Worm Fish", Tier = 7},
    [146] = {Name = "Strippled Seahorse", Tier = 5},
    [147] = {Name = "Thresher Shark", Tier = 5},
    [149] = {Name = "Angler Fish", Tier = 4},
    [150] = {Name = "Blob Fish", Tier = 6},
    [151] = {Name = "Boar Fish", Tier = 1},
    [152] = {Name = "Deep Sea Crab", Tier = 5},
    [153] = {Name = "Dark Eel", Tier = 2},
    [154] = {Name = "Electric Eel", Tier = 1},
    [155] = {Name = "Fangtooth", Tier = 4},
    [156] = {Name = "Giant Squid", Tier = 7},
    [157] = {Name = "Jellyfish", Tier = 3},
    [158] = {Name = "King Crab", Tier = 6},
    [159] = {Name = "Robot Kraken", Tier = 7},
    [160] = {Name = "Monk Fish", Tier = 4},
    [161] = {Name = "Spotted Lantern Fish", Tier = 2},
    [162] = {Name = "Vampire Squid", Tier = 4},
    [163] = {Name = "Viperfish", Tier = 2},
    [164] = {Name = "Swordfish", Tier = 2},
    [165] = {Name = "Skeleton Fish", Tier = 1},
    [166] = {Name = "Dead Fish", Tier = 1},
    [176] = {Name = "Ghost Worm Fish", Tier = 7},
    [182] = {Name = "Blackcap Basslet", Tier = 2},
    [183] = {Name = "Catfish", Tier = 3},
    [184] = {Name = "Coney Fish", Tier = 3},
    [185] = {Name = "Hermit Crab", Tier = 6},
    [186] = {Name = "Parrot Fish", Tier = 2},
    [187] = {Name = "Queen Crab", Tier = 7},
    [188] = {Name = "Red Snapper", Tier = 2},
    [189] = {Name = "Rockfish", Tier = 2},
    [190] = {Name = "Salmon", Tier = 2},
    [191] = {Name = "Sheepshead Fish", Tier = 3},
    [194] = {Name = "Barracuda Fish", Tier = 3},
    [195] = {Name = "Crystal Crab", Tier = 7},
    [196] = {Name = "Frog", Tier = 3},
    [197] = {Name = "Gar Fish", Tier = 2},
    [198] = {Name = "Herring Fish", Tier = 1},
    [199] = {Name = "Lake Sturgeon", Tier = 5},
    [200] = {Name = "Orca", Tier = 7},
}